//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open7x0Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string ftpUsername {
            get {
                return ((string)(this["ftpUsername"]));
            }
            set {
                this["ftpUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("l1nux")]
        public string ftpPassword {
            get {
                return ((string)(this["ftpPassword"]));
            }
            set {
                this["ftpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.4")]
        public string serveradress {
            get {
                return ((string)(this["serveradress"]));
            }
            set {
                this["serveradress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-vf dsize=4/3,scale=-10:-1,harddup -of lavf -lavfopts format=mp4 -ovc x264 -sws 9" +
            " -x264encopts nocabac:level_idc=30:bframes=0:bitrate=512:threads=auto:turbo=1:gl" +
            "obal_header:threads=auto")]
        public string mencoder4to3Parameter {
            get {
                return ((string)(this["mencoder4to3Parameter"]));
            }
            set {
                this["mencoder4to3Parameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-vf yadif,dsize=16/9,scale=-10:-1,harddup -of lavf -lavfopts format=mp4 -ovc x264" +
            " -sws 9 -x264encopts nocabac:level_idc=30:bframes=0:bitrate=900:threads=auto:tur" +
            "bo=1:global_header:threads=auto")]
        public string mencoder16to9Parameter {
            get {
                return ((string)(this["mencoder16to9Parameter"]));
            }
            set {
                this["mencoder16to9Parameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-oac faac -faacopts mpeg=4:object=2:raw:br=128")]
        public string mencoderStereoParameter {
            get {
                return ((string)(this["mencoderStereoParameter"]));
            }
            set {
                this["mencoderStereoParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-oac faac -faacopts mpeg=4:object=2:raw:br=256 -channels 6 -aid 128")]
        public string mencoderSurroundParameter {
            get {
                return ((string)(this["mencoderSurroundParameter"]));
            }
            set {
                this["mencoderSurroundParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--deinterlace=-1 --deinterlace-mode=x --play-and-exit --video-on-top")]
        public string vlcParameters {
            get {
                return ((string)(this["vlcParameters"]));
            }
            set {
                this["vlcParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe\"")]
        public string vlcPath {
            get {
                return ((string)(this["vlcPath"]));
            }
            set {
                this["vlcPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TestDaten")]
        public string localWorkingDirectory {
            get {
                return ((string)(this["localWorkingDirectory"]));
            }
            set {
                this["localWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/media/disk-volume-0/video")]
        public string remoteVideoRoot {
            get {
                return ((string)(this["remoteVideoRoot"]));
            }
            set {
                this["remoteVideoRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteOnEncoded {
            get {
                return ((bool)(this["DeleteOnEncoded"]));
            }
            set {
                this["DeleteOnEncoded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mp4")]
        public string mencoderOutputFileExtension {
            get {
                return ((string)(this["mencoderOutputFileExtension"]));
            }
            set {
                this["mencoderOutputFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%title% %eventID% %shortDescription% %autoIncrement%")]
        public string mencoderOutputFilename {
            get {
                return ((string)(this["mencoderOutputFilename"]));
            }
            set {
                this["mencoderOutputFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverwriteExistingOutputfile {
            get {
                return ((bool)(this["OverwriteExistingOutputfile"]));
            }
            set {
                this["OverwriteExistingOutputfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EncodeDolbyDigitalStreamWithSurroundSettings {
            get {
                return ((bool)(this["EncodeDolbyDigitalStreamWithSurroundSettings"]));
            }
            set {
                this["EncodeDolbyDigitalStreamWithSurroundSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShutdownAfterEncodingFinished {
            get {
                return ((bool)(this["ShutdownAfterEncodingFinished"]));
            }
            set {
                this["ShutdownAfterEncodingFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFtp {
            get {
                return ((bool)(this["UseFtp"]));
            }
            set {
                this["UseFtp"] = value;
            }
        }
    }
}
